In [1]:
import cv2
import random
import numpy as np
from matplotlib import pyplot as  plt

In [2]:
img_gray=cv2.imread('C:\\Users\\XYP\\Desktop\\photo\\xz1.jpeg',0)
#cv2.imshow('xiaozhan',img_gray)
#key = cv2.waitKey()
#cv2.destroyAllwindows()

In [3]:
print(img_gray)
print(img_gray.dtype)
print(img_gray.shape)

[[ 79  80  82 ...  86  83  83]
 [ 76  77  79 ...  83  83  83]
 [ 75  76  77 ...  80  82  82]
 ...
 [159 157 153 ...   9   8   8]
 [148 145 142 ...   8   8   8]
 [139 137 133 ...   7   8   8]]
uint8
(507, 490)


In [2]:
img=cv2.imread('C:\\Users\\XYP\\Desktop\\photo\\xz1.jpeg')
#cv2.imshow('xiaozhan1',img)

#img_crop=img[0:100,0:100]
#cv2.imshow('img_crop',img_crop)
#key=cv2.waitKey()
#cv2.destroyAllwindows()

In [ ]:
print(img)
print(img.dtype)
print(img.shape)

In [ ]:
img_crop=img[0:100,0:100]
cv2.imshow('img_crop',img_crop)
key=cv2.waitKey()
#cv2.destroyAllwindows()

In [ ]:
B,G,R=cv2.split(img)
cv2.imshow('B',B)
cv2.imshow('G',G)
cv2.imshow('R',R)
key=cv2.waitKey()
#cv2.destroyAllwindows()

In [ ]:
def random_light_color(img):
    B,G,R=cv2.split(img)
    b_rand=random.randint(-50,50)
    if b_rand==0:
        pass
    elif b_rand>0:
        lim=255-b_rand
        B[B>lim]=255
        B[B <= lim] = (b_rand + B[B <= lim]).astype(img.dtype)
    elif b_rand<0:
        lim = 0 - b_rand
        B[B < lim] = 0
        B[B >= lim] = (b_rand + B[B >= lim]).astype(img.dtype)
    g_rand = random.randint(-50, 50)
    if g_rand == 0:
        pass
    elif g_rand > 0:
        lim = 255 - g_rand
        G[G > lim] = 255
        G[G <= lim] = (g_rand + G[G <= lim]).astype(img.dtype)
    elif g_rand < 0:
        lim = 0 - g_rand
        G[G < lim] = 0
        G[G >= lim] = (g_rand + G[G >= lim]).astype(img.dtype) 
    r_rand = random.randint(-50, 50)
    if r_rand == 0:
        pass
    elif r_rand > 0:
        lim = 255 - r_rand
        R[R > lim] = 255
        R[R <= lim] = (r_rand + R[R <= lim]).astype(img.dtype)
    elif r_rand < 0:
        lim = 0 - r_rand
        R[R < lim] = 0
        R[R >= lim] = (r_rand + R[R >= lim]).astype(img.dtype)
    img_merge = cv2.merge((B, G, R))
    return  img_merge
img=cv2.imread('C:\\Users\\XYP\\Desktop\\photo\\xz1.jpeg')
img_random_color=random_light_color(img)
cv2.imshow('img_random_color',img_random_color)
key=cv2.waitKey()

In [2]:
img_dark=cv2.imread('C:\\Users\\XYP\\Desktop\\photo\\xz1.jpeg')
#cv2.imshow('img_dark', img_dark)
#key=cv2.waitKey()
def adjust_gamma(image,gamma=1.0):
    invGamma=1.0/gamma
    table=[]
    for i in range(256):
        table.append(((i / 255.0) ** invGamma)*255)
    table = np.array(table).astype("uint8")
    return cv2.LUT(image, table)
img_brighter = adjust_gamma(img_dark, 5)
#cv2.imshow('img_dark', img_dark)
#cv2.imshow('img_brighter', img_brighter)
#key = cv2.waitKey()

In [ ]:
img_small_brighter = cv2.resize(img_brighter, (int(img_brighter.shape[0]*1), int(img_brighter.shape[1]*1)))
plt.hist(img_brighter.flatten(), 256,[0,256]  ,color = 'r')
img_yuv = cv2.cvtColor(img_small_brighter, cv2.COLOR_BGR2YUV)
img_yuv[:,:,0] = cv2.equalizeHist(img_yuv[:,:,0]) 
img_output = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR)
cv2.imshow('Color input image', img_small_brighter)
cv2.imshow('Histogram equalized', img_output)
key = cv2.waitKey()

In [ ]:
M=cv2.getRotationMatrix2D((img.shape[0]/2,img.shape[1]/2),-30,1)
img_rotate = cv2.warpAffine(img, M, (img.shape[0], img.shape[1]))
cv2.imshow('img_rotate', img_rotate)

print(M)
#img_rotate2 = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
#cv2.imshow('rotated lenna2', img_rotate2)
key = cv2.waitKey()

[[  0.8660254   -0.5        156.46256014]
 [  0.5          0.8660254  -93.92622393]]


In [ ]:
rows, cols, ch = img.shape
pts1 = np.float32([[0, 0], [cols - 1, 0], [0, rows - 1]])
pts2 = np.float32([[cols * 0.2, rows * 0.1], [cols * 0.9, rows * 0.2], [cols * 0.1, rows * 0.9]])
 
M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(img, M, (cols, rows))

cv2.imshow('affine lenna', dst)
key = cv2.waitKey()

In [ ]:
def random_warp(img, row, col):
    height, width, channels = img.shape
    random_margin = 60
    x1 = random.randint(-random_margin, random_margin)
    y1 = random.randint(-random_margin, random_margin)
    x2 = random.randint(width - random_margin - 1, width - 1)
    y2 = random.randint(-random_margin, random_margin)
    x3 = random.randint(width - random_margin - 1, width - 1)
    y3 = random.randint(height - random_margin - 1, height - 1)
    x4 = random.randint(-random_margin, random_margin)
    y4 = random.randint(height - random_margin - 1, height - 1)

    dx1 = random.randint(-random_margin, random_margin)
    dy1 = random.randint(-random_margin, random_margin)
    dx2 = random.randint(width - random_margin - 1, width - 1)
    dy2 = random.randint(-random_margin, random_margin)
    dx3 = random.randint(width - random_margin - 1, width - 1)
    dy3 = random.randint(height - random_margin - 1, height - 1)
    dx4 = random.randint(-random_margin, random_margin)
    dy4 = random.randint(height - random_margin - 1, height - 1)

    pts1 = np.float32([[x1, y1], [x2, y2], [x3, y3], [x4, y4]])
    pts2 = np.float32([[dx1, dy1], [dx2, dy2], [dx3, dy3], [dx4, dy4]])
    M_warp = cv2.getPerspectiveTransform(pts1, pts2)
    img_warp = cv2.warpPerspective(img, M_warp, (width, height))
    return M_warp, img_warp
M_warp, img_warp = random_warp(img, img.shape[0], img.shape[1])
cv2.imshow('lenna_warp', img_warp)
key = cv2.waitKey()